groups:
  - name: host_alerts
    rules:
      - alert: HostHighCpuLoad
        # This expression calculates the percentage of non-idle CPU time over 5 minutes.
        # It's a more accurate measure of load than node_load1.
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 10m
        labels:
          severity: 'warning'
        annotations:
          summary: "Host high CPU load on {{ $labels.instance }}"
          description: "CPU usage has been above 85% for 10 minutes. Current value: {{ $value | printf \"%.2f\" }}%."

      - alert: HostOutOfMemory
        expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 < 10
        for: 5m
        labels:
          severity: 'critical'
        annotations:
          summary: "Host out of memory on {{ $labels.instance }}"
          description: "Available memory is less than 10%. Current value: {{ $value | printf \"%.2f\" }}%."

      - alert: HostHighDiskUsage
        # This expression ignores temporary filesystems to prevent false positives.
        expr: (node_filesystem_avail_bytes{mountpoint="/",fstype!~"tmpfs|squashfs"} / node_filesystem_size_bytes{mountpoint="/",fstype!~"tmpfs|squashfs"}) * 100 < 15
        for: 15m
        labels:
          severity: 'critical'
        annotations:
          summary: "Host high disk usage on {{ $labels.instance }}"
          description: "Root disk space is less than 15%. Current value: {{ $value | printf \"%.2f\" }}%."

      - alert: HostSystemDown
        # This alert fires if a node-exporter target has been unreachable for 5 minutes.
        expr: up{job="node-exporter"} == 0
        for: 5m
        labels:
          severity: 'critical'
        annotations:
          summary: "Host system down: {{ $labels.instance }}"
          description: "The node-exporter on {{ $labels.instance }} has been unreachable for more than 5 minutes."

  - name: container_alerts
    rules:
      - alert: ContainerCpuUsageHigh
        # This expression now groups by hostname AND name to preserve the host label.
        expr: sum by (hostname, name) (rate(container_cpu_usage_seconds_total{name!="", name!~"prometheus|grafana|cadvisor|alertmanager|node-exporter|portainer|dcgm-exporter"}[5m])) > 2
        for: 10m
        labels:
          severity: 'warning'
        annotations:
          summary: "High CPU on container {{ $labels.name }} on host {{ $labels.hostname }}"
          description: "Container '{{ $labels.name }}' on host '{{ $labels.hostname }}' has been using more than 2 CPU cores for 10 minutes."

      - alert: ContainerMemoryHigh
        # This expression now groups by hostname AND name to preserve the host label.
        expr: sum by (hostname, name) (container_memory_usage_bytes{name!="", name!~"prometheus|grafana|cadvisor|alertmanager|node-exporter|portainer|dcgm-exporter"}) > 4e9
        for: 10m
        labels:
          severity: 'warning'
        annotations:
          summary: "High memory on container {{ $labels.name }} on host {{ $labels.hostname }}"
          description: "Container '{{ $labels.name }}' on host '{{ $labels.hostname }}' is using more than 4GB of RAM. Current usage: {{ $value | humanize1024 }}B."

      - alert: ContainerKilled
        # This is a long-term fallback if a container disappears for 15 minutes.
        expr: time() - container_last_seen{name!="", name!~"prometheus|grafana|cadvisor|alertmanager|node-exporter|portainer|dcgm-exporter"} > 900
        for: 0m
        labels:
          severity: 'critical'
        annotations:
          summary: "App container {{ $labels.name }} on host {{ $labels.hostname }} has disappeared"
          description: "The application container '{{ $labels.name }}' on host '{{ $labels.hostname }}' has been missing for over 15 minutes. It may have crashed or been removed."

  - name: gpu_alerts
    rules:
      - alert: GpuHighTempWarning
        # This expression triggers if a specific GPU's temperature is above 80°C for 5 minutes.
        # It groups by 'instance' (the host) and 'gpu' (the specific card).
        expr: avg by (instance, gpu) (DCGM_FI_DEV_GPU_TEMP) > 36
        for: 5m
        labels:
          severity: 'warning'
        annotations:
          summary: "GPU high temperature warning on {{ $labels.instance }}"
          description: "GPU {{ $labels.gpu }} on host {{ $labels.instance }} has a temperature over 80°C. Current value: {{ $value | printf \"%.2f\" }}°C."

      - alert: GpuHighTempCritical
        # This expression triggers if a specific GPU's temperature is critically high (above 90°C).
        expr: avg by (instance, gpu) (DCGM_FI_DEV_GPU_TEMP) > 39
        for: 5m
        labels:
          severity: 'critical'
        annotations:
          summary: "GPU critical temperature on {{ $labels.instance }}"
          description: "GPU {{ $labels.gpu }} on host {{ $labels.instance }} has a critical temperature over 90°C. Current value: {{ $value | printf \"%.2f\" }}°C. Immediate action may be required."

      - alert: GpuSustainedHighUtilisation
        # This triggers if a GPU's utilization is over 90% for a sustained period of 15 minutes.
        # This can help identify workloads that may be stuck or unexpectedly consuming resources.
        expr: avg by (instance, gpu) (DCGM_FI_DEV_GPU_UTIL) > 90
        for: 15m
        labels:
          severity: 'warning'
        annotations:
          summary: "GPU sustained high utilisation on {{ $labels.instance }}"
          description: "GPU {{ $labels.gpu }} on host {{ $labels.instance }} has had utilisation above 90% for 15 minutes. Current value: {{ $value | printf \"%.2f\" }}%."