global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'dcgm-exporter'
    static_configs:
      - targets: ['dcgm-exporter:9400']

  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]

  # This job discovers remote nodes from the targets.json file
  # and applies relabeling to create clean job and hostname labels.
  - job_name: 'remote-nodes'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets.json'
    relabel_configs:
      # This rule takes the 'job' label from targets.json and uses it as the actual job name.
      - source_labels: [job]
        target_label: job
        replacement: '${1}'
      # This rule creates a clean 'hostname' label from the target's IP address.
      - source_labels: [__address__]
        regex: '([^:]+):.*'  # Captures the IP address part (everything before the colon).
        target_label: hostname # Creates a new label called 'hostname'.
        replacement: '${1}'    # Sets the value of 'hostname' to the captured IP.

