{
 "title": "Simplified Host Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "query_result(count_over_time(up[5m]) > 0)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OS Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_os_info{servername=\"$host\"}",
     "legendFormat": "{{pretty_name}}"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{servername=\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{servername=\"$host\", mode='system'})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{servername=\"$host\"} - node_memory_MemAvailable_bytes{servername=\"$host\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{servername=\"$host\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{servername=\"$host\", fstype!~\"tmpfs|squashfs\"}) - sum(node_filesystem_free_bytes{servername=\"$host\", fstype!~\"tmpfs|squashfs\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{servername=\"$host\", fstype!~\"tmpfs|squashfs\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{job=\"dcgm-exporter-remote\", servername=\"$host\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{job=\"dcgm-exporter-remote\", servername=\"$host\"}",
     "legendFormat": "{{device}}: {{modelName}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", servername=\"$host\"}[5m])) * 100)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (DCGM_FI_DEV_FB_USED{job=\"dcgm-exporter-remote\", servername=\"$host\"} / (DCGM_FI_DEV_FB_USED{job=\"dcgm-exporter-remote\", servername=\"$host\"} + DCGM_FI_DEV_FB_FREE{job=\"dcgm-exporter-remote\", servername=\"$host\"}))",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{job=\"dcgm-exporter-remote\", servername=\"$host\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "Running Containers (cAdvisor)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Container Resource Consumption",
   "type": "table",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{servername=\"$host\",name!=\"\"}[1m]))"
    },
    {
     "expr": "sum(container_memory_usage_bytes{servername=\"$host\", name!=\"\"}) by (name)"
    },
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{servername=\"$host\", name!=\"\"}[1m]))"
    },
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{servername=\"$host\", name!=\"\"}[1m]))"
    },
    {
     "expr": "time() - avg(container_start_time_seconds{servername=\"$host\", name!=\"\"}) by (name)"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{servername=\"$host\"}[5m])",
     "legendFormat": "Read - {{device}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{servername=\"$host\"}[5m])",
     "legendFormat": "Write - {{device}}"
    }
   ]
  }
 ]
}